-- ==============================================================================
-- SARI-SARI / COLDCUT POS — HARDENED SUPABASE DISASTER RECOVERY & CLOUD BACKEND
-- ==============================================================================
-- Run this script in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/<your-project-id>/sql/new
-- ==============================================================================

-- 1. STORAGE BUCKET: store-backups (PRIVATE)
-- Encrypted SQLite store.db snapshot backups. Access restricted to authorized roles.
INSERT INTO storage.buckets (id, name, public)
VALUES ('store-backups', 'store-backups', false)
ON CONFLICT (id) DO UPDATE SET public = false;

-- Clean up any legacy permissive storage policies
DROP POLICY IF EXISTS "Allow public read from store-backups" ON storage.objects;
DROP POLICY IF EXISTS "Allow uploads to store-backups" ON storage.objects;
DROP POLICY IF EXISTS "Allow updates to store-backups" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated read store-backups" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated insert store-backups" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated update store-backups" ON storage.objects;

-- Enforce authenticated role for storage operations (service_role bypasses RLS)
CREATE POLICY "Allow authenticated read store-backups"
ON storage.objects FOR SELECT
TO authenticated
USING (bucket_id = 'store-backups');

CREATE POLICY "Allow authenticated insert store-backups"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'store-backups');

CREATE POLICY "Allow authenticated update store-backups"
ON storage.objects FOR UPDATE
TO authenticated
USING (bucket_id = 'store-backups');


-- 2. CLOUD DATABASE TABLES (Standalone Cloud POS & Disaster Recovery)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.products (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode             TEXT,
    pack_barcode        TEXT,
    jar_code            TEXT,
    name                TEXT NOT NULL,
    category            TEXT DEFAULT 'General',
    unit                TEXT NOT NULL DEFAULT 'pc',
    cost_price          NUMERIC(12, 2) NOT NULL DEFAULT 0,
    selling_price       NUMERIC(12, 2) NOT NULL DEFAULT 0,
    stock_qty           NUMERIC(12, 3) NOT NULL DEFAULT 0,
    low_stock_threshold NUMERIC(12, 3) NOT NULL DEFAULT 5,
    is_quick_item       BOOLEAN NOT NULL DEFAULT false,
    quick_button_color  TEXT DEFAULT '#3b82f6',
    pcs_per_pack        INTEGER DEFAULT 1,
    bulk_cost_price     NUMERIC(12, 2),
    full_pack_price     NUMERIC(12, 2),
    half_dozen_price    NUMERIC(12, 2),
    dozen_price         NUMERIC(12, 2),
    plu_code            INTEGER,
    freezer_section     TEXT DEFAULT 'Frozen Main',
    refill_price        NUMERIC(12, 2),
    refill_qty          NUMERIC(12, 3) DEFAULT 1.0,
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure all columns exist if products table was created previously
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_quick_item BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS quick_button_color TEXT DEFAULT '#3b82f6';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS pcs_per_pack INTEGER DEFAULT 1;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS bulk_cost_price NUMERIC(12, 2);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS full_pack_price NUMERIC(12, 2);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS half_dozen_price NUMERIC(12, 2);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS dozen_price NUMERIC(12, 2);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS plu_code INTEGER;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS freezer_section TEXT DEFAULT 'Frozen Main';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS refill_price NUMERIC(12, 2);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS refill_qty NUMERIC(12, 3) DEFAULT 1.0;

CREATE TABLE IF NOT EXISTS public.transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_number      TEXT,
    transaction_type    TEXT NOT NULL DEFAULT 'SALE',
    total_amount        NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_cost          NUMERIC(12, 2) NOT NULL DEFAULT 0,
    payment_method      TEXT DEFAULT 'CASH',
    amount_tendered     NUMERIC(12, 2) NOT NULL DEFAULT 0,
    change_amount       NUMERIC(12, 2) NOT NULL DEFAULT 0,
    customer_name       TEXT,
    notes               TEXT,
    receipt_printed     BOOLEAN DEFAULT false,
    created_at          TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.transaction_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id      BIGINT REFERENCES public.transactions(id) ON DELETE CASCADE,
    product_name        TEXT NOT NULL,
    quantity            NUMERIC(12, 3) NOT NULL DEFAULT 1,
    unit_price          NUMERIC(12, 2) NOT NULL DEFAULT 0,
    cost_price          NUMERIC(12, 2) NOT NULL DEFAULT 0,
    subtotal            NUMERIC(12, 2) NOT NULL DEFAULT 0,
    pack_label          TEXT
);

CREATE TABLE IF NOT EXISTS public.customer_debts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name       TEXT NOT NULL UNIQUE,
    total_debt          NUMERIC(12, 2) NOT NULL DEFAULT 0,
    phone_number        TEXT,
    notes               TEXT,
    updated_at          TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.debt_transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debt_id             BIGINT REFERENCES public.customer_debts(id) ON DELETE CASCADE,
    sale_id             BIGINT,
    type                TEXT NOT NULL,
    amount              NUMERIC(12, 2) NOT NULL,
    balance_after       NUMERIC(12, 2) NOT NULL,
    notes               TEXT,
    created_at          TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.gcash_transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id      BIGINT REFERENCES public.transactions(id) ON DELETE CASCADE,
    flow_type           TEXT NOT NULL,
    input_amount        NUMERIC(12, 2) NOT NULL,
    principal_amount    NUMERIC(12, 2) NOT NULL,
    fee                 NUMERIC(12, 2) NOT NULL,
    total_collected     NUMERIC(12, 2) NOT NULL,
    reference_number    TEXT,
    mobile_number       TEXT,
    created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_cloud_products_barcode ON public.products(barcode);
CREATE INDEX IF NOT EXISTS idx_cloud_products_pack_barcode ON public.products(pack_barcode);
CREATE INDEX IF NOT EXISTS idx_cloud_products_plu ON public.products(plu_code);
CREATE INDEX IF NOT EXISTS idx_cloud_products_quick ON public.products(is_quick_item);
CREATE INDEX IF NOT EXISTS idx_cloud_txns_created_at ON public.transactions(created_at);
CREATE INDEX IF NOT EXISTS idx_cloud_txn_items_txnid ON public.transaction_items(transaction_id);
CREATE INDEX IF NOT EXISTS idx_cloud_debts_customer ON public.customer_debts(customer_name);


-- 3. ROW LEVEL SECURITY (RLS) & ACCESS HARDENING
-- ==============================================================================

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transaction_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_debts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.debt_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gcash_transactions ENABLE ROW LEVEL SECURITY;

-- Clean legacy policies
DROP POLICY IF EXISTS "Allow public read on products" ON public.products;
DROP POLICY IF EXISTS "Allow authenticated write products" ON public.products;
DROP POLICY IF EXISTS "Allow read on transactions" ON public.transactions;
DROP POLICY IF EXISTS "Allow read on transaction_items" ON public.transaction_items;
DROP POLICY IF EXISTS "Allow read on customer_debts" ON public.customer_debts;
DROP POLICY IF EXISTS "Allow read on debt_transactions" ON public.debt_transactions;
DROP POLICY IF EXISTS "Allow read on gcash_transactions" ON public.gcash_transactions;

-- Read policies (Cashier tablets and clients can query data)
CREATE POLICY "Allow public read on products"
ON public.products FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "Allow authenticated write products"
ON public.products FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow read on transactions"
ON public.transactions FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "Allow read on transaction_items"
ON public.transaction_items FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "Allow read on customer_debts"
ON public.customer_debts FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "Allow read on debt_transactions"
ON public.debt_transactions FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "Allow read on gcash_transactions"
ON public.gcash_transactions FOR SELECT
TO anon, authenticated
USING (true);

-- Permissions
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon;
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON public.products TO anon, authenticated;
GRANT SELECT ON public.transactions TO anon, authenticated;
GRANT SELECT ON public.transaction_items TO anon, authenticated;
GRANT SELECT ON public.customer_debts TO anon, authenticated;
GRANT SELECT ON public.debt_transactions TO anon, authenticated;
GRANT SELECT ON public.gcash_transactions TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;


-- 4. ATOMIC POSTGRES STORED PROCEDURES (RPCs for Standalone Cloud POS)
-- ==============================================================================

-- A. ATOMIC CHECKOUT ENGINE
CREATE OR REPLACE FUNCTION public.process_checkout(payload JSONB)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_receipt_number TEXT;
    v_total_amount NUMERIC(12, 2);
    v_total_cost NUMERIC(12, 2) := 0;
    v_amount_tendered NUMERIC(12, 2);
    v_payment_method TEXT;
    v_customer_name TEXT;
    v_notes TEXT;
    v_txn_id BIGINT;
    v_item JSONB;
    v_qty NUMERIC(12, 3);
    v_unit_price NUMERIC(12, 2);
    v_cost_price NUMERIC(12, 2);
    v_subtotal NUMERIC(12, 2);
    v_prod_id BIGINT;
    v_debt_id BIGINT;
    v_new_debt_balance NUMERIC(12, 2);
BEGIN
    -- 1. Validate payload basics
    IF payload IS NULL OR NOT (payload ? 'items') OR jsonb_array_length(payload->'items') = 0 THEN
        RAISE EXCEPTION 'Checkout rejected: Cart cannot be empty.';
    END IF;

    v_total_amount := (payload->>'total_amount')::numeric;
    v_amount_tendered := COALESCE((payload->>'amount_tendered')::numeric, v_total_amount);
    v_payment_method := UPPER(COALESCE(payload->>'payment_method', 'CASH'));
    v_customer_name := NULLIF(TRIM(payload->>'customer_name'), '');
    v_notes := payload->>'notes';

    IF v_total_amount < 0 THEN
        RAISE EXCEPTION 'Checkout rejected: Total amount cannot be negative.';
    END IF;

    IF v_payment_method = 'UTANG' AND (v_customer_name IS NULL OR v_customer_name = '') THEN
        RAISE EXCEPTION 'Checkout rejected: Customer name is required for Utang (Debt) sales.';
    END IF;

    -- 2. Calculate COGS & validate items
    FOR v_item IN SELECT * FROM jsonb_array_elements(payload->'items')
    LOOP
        v_qty := (v_item->>'quantity')::numeric;
        v_unit_price := (v_item->>'unit_price')::numeric;
        v_cost_price := COALESCE((v_item->>'cost_price')::numeric, 0);

        IF v_qty <= 0 THEN
            RAISE EXCEPTION 'Checkout rejected: Item quantity must be greater than zero.';
        END IF;
        IF v_unit_price < 0 THEN
            RAISE EXCEPTION 'Checkout rejected: Unit price cannot be negative.';
        END IF;

        v_total_cost := v_total_cost + (v_cost_price * v_qty);
    END LOOP;

    -- 3. Generate receipt number
    v_receipt_number := 'RCP-' || to_char(NOW(), 'YYYYMMDD') || '-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 6));

    -- 4. Insert transaction record
    INSERT INTO public.transactions (
        receipt_number,
        transaction_type,
        total_amount,
        total_cost,
        payment_method,
        amount_tendered,
        change_amount,
        customer_name,
        notes,
        created_at
    ) VALUES (
        v_receipt_number,
        'SALE',
        v_total_amount,
        v_total_cost,
        v_payment_method,
        v_amount_tendered,
        GREATEST(0, v_amount_tendered - v_total_amount),
        v_customer_name,
        v_notes,
        NOW()
    ) RETURNING id INTO v_txn_id;

    -- 5. Insert line items & decrement stock
    FOR v_item IN SELECT * FROM jsonb_array_elements(payload->'items')
    LOOP
        v_qty := (v_item->>'quantity')::numeric;
        v_unit_price := (v_item->>'unit_price')::numeric;
        v_cost_price := COALESCE((v_item->>'cost_price')::numeric, 0);
        v_subtotal := COALESCE((v_item->>'subtotal')::numeric, v_qty * v_unit_price);
        v_prod_id := NULLIF(v_item->>'product_id', '')::bigint;

        INSERT INTO public.transaction_items (
            transaction_id,
            product_name,
            quantity,
            unit_price,
            cost_price,
            subtotal,
            pack_label
        ) VALUES (
            v_txn_id,
            v_item->>'product_name',
            v_qty,
            v_unit_price,
            v_cost_price,
            v_subtotal,
            v_item->>'pack_label'
        );

        -- Decrement stock in catalog if product exists
        IF v_prod_id IS NOT NULL AND v_prod_id > 0 THEN
            UPDATE public.products
            SET stock_qty = stock_qty - v_qty,
                updated_at = NOW()
            WHERE id = v_prod_id;
        END IF;
    END LOOP;

    -- 6. Record Customer Utang (Debt) if applicable
    IF v_payment_method = 'UTANG' THEN
        INSERT INTO public.customer_debts (customer_name, total_debt, phone_number, notes, updated_at)
        VALUES (v_customer_name, v_total_amount, payload->>'phone_number', v_notes, NOW())
        ON CONFLICT (customer_name)
        DO UPDATE SET total_debt = customer_debts.total_debt + EXCLUDED.total_debt,
                      updated_at = NOW()
        RETURNING id, total_debt INTO v_debt_id, v_new_debt_balance;

        INSERT INTO public.debt_transactions (
            debt_id,
            sale_id,
            type,
            amount,
            balance_after,
            notes,
            created_at
        ) VALUES (
            v_debt_id,
            v_txn_id,
            'CHARGE',
            v_total_amount,
            v_new_debt_balance,
            'POS Sale: ' || v_receipt_number,
            NOW()
        );
    END IF;

    -- 7. Return completed transaction payload
    RETURN jsonb_build_object(
        'id', v_txn_id,
        'receipt_number', v_receipt_number,
        'total_amount', v_total_amount,
        'amount_tendered', v_amount_tendered,
        'change', GREATEST(0, v_amount_tendered - v_total_amount),
        'change_amount', GREATEST(0, v_amount_tendered - v_total_amount),
        'payment_method', v_payment_method,
        'customer_name', v_customer_name,
        'created_at', NOW(),
        'items', payload->'items'
    );
END;
$$;


-- B. DEBT REPAYMENT ENGINE
CREATE OR REPLACE FUNCTION public.pay_customer_debt(
    p_debt_id BIGINT,
    p_payment_amount NUMERIC,
    p_notes TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_cust RECORD;
    v_new_balance NUMERIC(12, 2);
    v_receipt_number TEXT;
    v_txn_id BIGINT;
BEGIN
    IF p_payment_amount <= 0 THEN
        RAISE EXCEPTION 'Payment amount must be greater than zero.';
    END IF;

    SELECT * INTO v_cust FROM public.customer_debts WHERE id = p_debt_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Customer debt record not found.';
    END IF;

    v_new_balance := GREATEST(0, v_cust.total_debt - p_payment_amount);

    UPDATE public.customer_debts
    SET total_debt = v_new_balance,
        updated_at = NOW()
    WHERE id = p_debt_id;

    v_receipt_number := 'PAY-' || to_char(NOW(), 'YYYYMMDD') || '-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 6));

    -- Record transaction
    INSERT INTO public.transactions (
        receipt_number,
        transaction_type,
        total_amount,
        payment_method,
        amount_tendered,
        change_amount,
        customer_name,
        notes,
        created_at
    ) VALUES (
        v_receipt_number,
        'UTANG_PAYMENT',
        p_payment_amount,
        'CASH',
        p_payment_amount,
        0,
        v_cust.customer_name,
        COALESCE(p_notes, 'Debt repayment: ' || v_receipt_number),
        NOW()
    ) RETURNING id INTO v_txn_id;

    INSERT INTO public.debt_transactions (
        debt_id,
        sale_id,
        type,
        amount,
        balance_after,
        notes,
        created_at
    ) VALUES (
        p_debt_id,
        v_txn_id,
        'PAYMENT',
        p_payment_amount,
        v_new_balance,
        COALESCE(p_notes, 'Debt repayment: ' || v_receipt_number),
        NOW()
    );

    RETURN jsonb_build_object(
        'message', 'Payment recorded successfully',
        'customer', jsonb_build_object(
            'id', v_cust.id,
            'customer_name', v_cust.customer_name,
            'total_debt', v_new_balance
        ),
        'payment_amount', p_payment_amount
    );
END;
$$;


-- C. GCASH TRANSACTION ENGINE
CREATE OR REPLACE FUNCTION public.record_gcash_transaction(payload JSONB)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_txn_id BIGINT;
    v_gcash_id BIGINT;
    v_receipt_number TEXT;
    v_flow_type TEXT;
    v_input_amount NUMERIC(12, 2);
    v_principal NUMERIC(12, 2);
    v_fee NUMERIC(12, 2);
    v_total_collected NUMERIC(12, 2);
BEGIN
    v_flow_type := UPPER(payload->>'flow_type');
    v_input_amount := (payload->>'input_amount')::numeric;
    v_principal := (payload->>'principal_amount')::numeric;
    v_fee := COALESCE((payload->>'fee')::numeric, 0);
    v_total_collected := COALESCE((payload->>'total_collected')::numeric, v_input_amount + v_fee);

    v_receipt_number := 'GCASH-' || to_char(NOW(), 'YYYYMMDD') || '-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 6));

    INSERT INTO public.transactions (
        receipt_number,
        transaction_type,
        total_amount,
        total_cost,
        payment_method,
        amount_tendered,
        change_amount,
        notes,
        created_at
    ) VALUES (
        v_receipt_number,
        CASE WHEN v_flow_type = 'IN' THEN 'GCASH_IN' ELSE 'GCASH_OUT' END,
        v_total_collected,
        0,
        'GCASH',
        v_total_collected,
        0,
        'GCash Ref: ' || COALESCE(payload->>'reference_number', 'N/A'),
        NOW()
    ) RETURNING id INTO v_txn_id;

    INSERT INTO public.gcash_transactions (
        transaction_id,
        flow_type,
        input_amount,
        principal_amount,
        fee,
        total_collected,
        reference_number,
        mobile_number,
        created_at
    ) VALUES (
        v_txn_id,
        v_flow_type,
        v_input_amount,
        v_principal,
        v_fee,
        v_total_collected,
        payload->>'reference_number',
        payload->>'mobile_number',
        NOW()
    ) RETURNING id INTO v_gcash_id;

    RETURN jsonb_build_object(
        'success', true,
        'transaction_id', v_txn_id,
        'gcash_id', v_gcash_id,
        'receipt_number', v_receipt_number,
        'flow_type', v_flow_type,
        'principal_amount', v_principal,
        'fee', v_fee,
        'total_collected', v_total_collected
    );
END;
$$;

-- Grant execution rights to frontend clients
GRANT EXECUTE ON FUNCTION public.process_checkout(JSONB) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_customer_debt(BIGINT, NUMERIC, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_gcash_transaction(JSONB) TO anon, authenticated;
